/* eslint-disable global-require */
module.exports = {
  http_request_incoming: require('./http_request_incoming'),
  http_send_response: require('./http_send_response'),
  project_error: require('./project_error'),
  rpc_response: require('./rpc_response'),
  sandbox_exited: require('./sandbox_exited'),
  sandbox_started: require('./sandbox_started'),
  sandbox_stderr: require('./sandbox_stderr'),
  server_listening: require('./server_listening'),
  server_package: require('./server_package'),
  session_response: require('./session_response'),
  svclib_interface: require('./svclib_interface'),
  svclib_request: require('./svclib_request'),
  svclib_response: require('./svclib_response'),
  svclib_event: require('./svclib_event'),
  user_event: require('./user_event'),
  ws_connection_started: require('./ws_connection_started'),
  ws_connection_ended: require('./ws_connection_ended'),
  ws_message_incoming: require('./ws_message_incoming'),
};
