
// ===========================================================
// WARNING: THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.
// ===========================================================

module.exports = {
  get: require('./get'),
  set: require('./set'),
  update: require('./update'),
};

