var def = require('runtype').schemaDef;

module.exports = {
  accepts: [
    def.TypedArray([
      def.Literal('start_sandbox'),
      def.Type('UserlandBootstrap'),
    ]),
    def.TypedArray([
      def.Literal('rpc_request'),
      def.Type('RpcRequest'),
    ]),
    def.TypedArray([
      def.Literal('session_request'),
      def.Type('any'),
    ]),
    def.TypedArray([
      def.Literal('svclib_response'),
      def.Type('SvclibResponse'),
    ]),
    def.TypedArray([
      def.Literal('svclib_event'),
      def.Type('any'),
    ]),
    def.TypedArray([
      def.Literal('stop_sandbox'),
    ]),
  ],
  emits: [
    def.TypedArray([
      def.Literal('sandbox_started'),
    ]),
    def.TypedArray([
      def.Literal('sandbox_exited'),
      def.Type('any'),
    ]),
    def.TypedArray([
      def.Literal('sandbox_stdout'),
      def.Type('any'),
    ]),
    def.TypedArray([
      def.Literal('sandbox_stderr'),
      def.Type('any'),
    ]),
    def.TypedArray([
      def.Literal('svclib_request'),
      def.Type('SvclibRequest'),
    ]),
    def.TypedArray([
      def.Literal('rpc_response'),
      def.Type('RpcResponse'),
    ]),
    def.TypedArray([
      def.Literal('session_response'),
      def.Type('any'),
    ]),
    def.TypedArray([
      def.Literal('user_event'),
      def.Type('UserEvent'),
    ]),
  ],
};
